services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ./notebooks:/opt/notebooks
      - ./data:/opt/data
    networks:
      - spark-network
    command: >
      /bin/bash -c " /opt/spark/sbin/start-master.sh && tail -f /opt/spark/logs/* "

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g #antes estaba a 4
      - SPARK_WORKER_WEBUI_PORT=8081
    deploy:
      replicas: 1 #antes estaba en 3
    depends_on:
      - spark-master
    volumes:
      - ./notebooks:/opt/notebooks
      - ./data:/opt/data
    networks:
      - spark-network
    command: >
      /bin/bash -c " /opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /opt/spark/logs/* "

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-spark
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8888:8888" # Jupyter Lab
      - "4040:4040" # Spark Application UI
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-network
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

networks:
  spark-network:
    driver: bridge
